version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: StrongPassword123
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data
    networks:
      - app-management-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 30s
      timeout: 10s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: StrongPassword123
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"       # disabilita restrizione hostname per dev
      KC_LOG_LEVEL: DEBUG               # livello log per debug, cambia in produzione
    command: start-dev                  # modalità dev per partenza rapida
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-management-network

volumes:
  keycloak-postgres-data:

networks:
  app-management-network:
    driver: bridge
