server:
  port: 8761
spring:
  application:
    name: app-management-eureka
  profiles:
    active: development
eureka:
  client:
    register-with-eureka: false  
    fetch-registry: false        
  server:
    enable-self-preservation: false  
