server:
  port: 8585
spring:
  application:
    name: app-management-keycloack-listener
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8090/realms/dashboard

logging:
  level:
    root: INFO
    it.eus.app_management_keycloack_listener: INFO
