management:
  info:
    env:
      enabled: true
  server:
    port: 7703
  endpoints:
    web:
      base-path: /app-management-gateway-info
      exposure:
        include: health,info,metrics,prometheus,env
  endpoint:
    health:
      show-details: when-authorized

spring:
  config:
    import: "optional:configserver:http://config-server:8888"
  security:
    user:
      name: ${GATEWAY_SECURITY_USER}
      password: ${GATEWAY_SECURITY_PASSWORD}
      roles: ACTUATOR
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8090/realms/dashboard
      client:
        registration:
          keycloak:
            client-id: dashboard-gateway
            client-secret: gateway-secret-key
            authorization-grant-type: client_credentials
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://keycloak:8090/realms/dashboard

info:
  name: ${spring.application.name:eureka-server}
  version: ${spring.application.version:1.0.0}
  description: "Service Eureka Server per discovery"
  maintainer: "Roberto <roberto@example.com>"
  build.time: "${BUILD_TIME:-unknown}"

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SECURITY_USER}:${EUREKA_SECURITY_PASSWORD}@eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
